@startuml
 Tristram <--> AlphaCentauri: 34
 Tristram <--> Snowdin: 100
 Tristram <--> Faerun: 108
 Tristram <--> Tambi: 63
 Tristram <--> Arbre: 132
 Tristram <--> Norrath: 111
 Tristram <--> Straylight: 89
 AlphaCentauri <--> Tristram: 34
 AlphaCentauri <--> Snowdin: 4
 AlphaCentauri <--> Faerun: 44
 AlphaCentauri <--> Tambi: 79
 AlphaCentauri <--> Arbre: 74
 AlphaCentauri <--> Norrath: 147
 AlphaCentauri <--> Straylight: 133
 Faerun <--> Tristram: 108
 Faerun <--> AlphaCentauri: 44
 Faerun <--> Snowdin: 95
 Faerun <--> Tambi: 68
 Faerun <--> Arbre: 144
 Faerun <--> Norrath: 11
 Faerun <--> Straylight: 66
 Snowdin <--> Tristram: 100
 Snowdin <--> AlphaCentauri: 4
 Snowdin <--> Faerun: 95
 Snowdin <--> Tambi: 105
 Snowdin <--> Arbre: 7
 Snowdin <--> Norrath: 48
 Snowdin <--> Straylight: 88
 Tambi <--> Tristram: 63
 Tambi <--> AlphaCentauri: 79
 Tambi <--> Snowdin: 105
 Tambi <--> Faerun: 68
 Tambi <--> Arbre: 40
 Tambi <--> Norrath: 134
 Tambi <--> Straylight: 107
 Arbre <--> Tristram: 132
 Arbre <--> AlphaCentauri: 74
 Arbre <--> Snowdin: 7
 Arbre <--> Faerun: 144
 Arbre <--> Tambi: 40
 Arbre <--> Norrath: 135
 Arbre <--> Straylight: 127
 Straylight <--> Tristram: 89
 Straylight <--> AlphaCentauri: 133
 Straylight <--> Snowdin: 88
 Straylight <--> Faerun: 66
 Straylight <--> Tambi: 107
 Straylight <--> Arbre: 127
 Straylight <--> Norrath: 115
 Norrath <--> Tristram: 111
 Norrath <--> AlphaCentauri: 147
 Norrath <--> Snowdin: 48
 Norrath <--> Faerun: 11
 Norrath <--> Tambi: 134
 Norrath <--> Arbre: 135
 Norrath <--> Straylight: 115
@enduml
