@startuml
rectangle dd <<Con>>
rectangle broadcaster
rectangle lp <<F-F>>
rectangle hq <<F-F>>
rectangle dq <<F-F>>
rectangle lz <<Con>>
rectangle output
rectangle qc <<F-F>>
rectangle dv <<F-F>>
rectangle mb <<F-F>>
rectangle qh <<F-F>>
rectangle mh <<F-F>>
rectangle qm <<F-F>>
rectangle mj <<F-F>>
rectangle qr <<Con>>
rectangle mv <<F-F>>
rectangle vb <<F-F>>
rectangle zj <<F-F>>
rectangle vg <<F-F>>
rectangle vl <<F-F>>
rectangle rn <<F-F>>
rectangle fb <<F-F>>
rectangle nk <<F-F>>
rectangle jj <<F-F>>
rectangle rr <<F-F>>
rectangle nr <<F-F>>
rectangle rv <<F-F>>
rectangle jn <<F-F>>
rectangle rx
rectangle jq <<Con>>
rectangle nx <<Con>>
rectangle fr <<F-F>>
rectangle ft <<Con>>
rectangle jx <<F-F>>
rectangle sb <<F-F>>
rectangle fx <<F-F>>
rectangle bz <<F-F>>
rectangle sn <<F-F>>
rectangle sp <<Con>>
rectangle cc <<Con>>
rectangle gm <<F-F>>
rectangle sz <<F-F>>
rectangle kr <<F-F>>
rectangle ks <<F-F>>
rectangle cl <<F-F>>
rectangle xc <<F-F>>
rectangle gx <<F-F>>
rectangle xk <<F-F>>
rectangle pc <<F-F>>
rectangle xl <<F-F>>
rectangle xn <<F-F>>
rectangle lb <<F-F>>
rectangle cz <<F-F>>
rectangle xt <<F-F>>
rectangle hd <<F-F>>
rectangle pl <<F-F>>
rectangle lh <<F-F>>
rectangle db <<F-F>>
rectangle ts <<F-F>>
rectangle lk <<Con>>

dd --> rx
broadcaster --> cz
broadcaster --> gm
broadcaster --> jn
broadcaster --> ts
lp --> sb
hq --> ft
hq --> lh
dq --> qr
dq --> rv
lz --> gx
lz --> xn
lz --> jq
lz --> fb
lz --> ts
lz --> rr
qc --> pl
qc --> ft
dv --> lz
dv --> hd
mb --> qr
mb --> jj
qh --> ft
qh --> qc
mh --> lk
mh --> vg
qm --> db
qm --> lk
mj --> dq
mj --> qr
qr --> cz
qr --> sp
qr --> lb
qr --> xt
qr --> fx
mv --> lz
mv --> rr
vb --> lz
vb --> xn
zj --> fx
zj --> qr
vg --> lk
vg --> ks
vl --> zj
vl --> qr
rn --> qm
fb --> vb
nk --> mv
nk --> lz
jj --> qr
jj --> mj
rr --> gx
nr --> hq
rv --> qr
jn --> sz
jn --> ft
jq --> dd
nx --> dd
fr --> ft
ft --> jx
ft --> nx
ft --> lh
ft --> pc
ft --> nr
ft --> jn
ft --> kr
jx --> kr
sb --> lk
sb --> rn
fx --> bz
bz --> lb
bz --> qr
sn --> lp
sp --> dd
cc --> dd
gm --> lk
gm --> cl
sz --> nr
sz --> ft
kr --> pc
ks --> lk
cl --> xk
xc --> lz
gx --> fb
xk --> sn
pc --> qh
xl --> dv
xl --> lz
xn --> xl
lb --> mb
cz --> xt
cz --> qr
xt --> vl
hd --> lz
hd --> xc
pl --> ft
pl --> fr
lh --> jx
db --> mh
db --> lk
ts --> lz
ts --> nk
lk --> sn
lk --> cc
lk --> xk
lk --> rn
lk --> gm
lk --> cl
lk --> lp
@enduml
